config/routes.rb
Rails.application.routes.draw do

  resources :snapshot_comments

  mount Upmin::Engine => '/admin'

  root to: 'visitors#index'

  post "/users/me" => "users#me"
  get "/users/feed" => "users#feed"
  get "/users/:user_id/friends" => "users#friends"
  get "/users/friends" => "users#friends"
  get "/users/:user_id/followers" => "users#followers"
  get "/users/followers" => "users#followers"
  get "/users/media" => "users#media"
  get "/users/:user_id/media" => "users#media"
  get "/friend/:friend_id" => "users#friend"
  post "/users/:user_id/follow" => "users#follow"
  post "/users/:user_id/unfollow" => "users#unfollow"
  post "/users/near_me" => "users#near_me"
  post "/users/register_notifications" => "users#register_notifications"
  post "/users/unregister_notifications" => "users#unregister_notifications"
  post "/password/reset" => "passwords#reset_password"


  post "/followings/approve/:user_id" => "followings#approve"
  post "/followings/decline/:user_id" => "followings#decline"

  get "/schools/:school_id/members" => "schools#members"

  post "/schools/:school_id/follow" => "schools#follow"
  post "/schools/:school_id/unfollow" => "schools#unfollow"

  post "/comments/:comment_id/flag" => "comments#flag"
  post "/comments/:comment_id/unflag" => "comments#unflag"

  post "/comments/:comment_id/like" => "comments#like"
  post "/comments/:comment_id/unlike" => "comments#unlike"

  post "/comments/:comment_id/dislike" => "comments#dislike"
  post "/comments/:comment_id/undislike" => "comments#undislike"

  post "/snapshots/:snapshot_id/flag" => "snapshots#flag"
  post "/snapshots/:snapshot_id/unflag" => "snapshots#unflag"

  post "/snapshots/:snapshot_id/like" => "snapshots#like"
  post "/snapshots/:snapshot_id/unlike" => "snapshots#unlike"

  post "/snapshots/:snapshot_id/dislike" => "snapshots#dislike"
  post "/snapshots/:snapshot_id/undislike" => "snapshots#undislike"

  get "/snapshots/:snapshot_id/feed" => "snapshots#feed"

  get "/messages/:recipient_id/chat" => "messages#chat"
  post "/messages/:id/time" => "messages#viewed_time"


  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}

  resources :users
  resources :snapshots
  resources :comments
  resources :schools
  resources :messages
  resources :followings


end

app/models/following.rb
class Following < ActiveRecord::Base

  belongs_to :user
  belongs_to :followed, :class_name => 'User'

  # member 'status' can have the following values:
  # null - this record should be removed
  # "requested" - the initiating party has requested the follow (recipient is a private user only)
  # "approved" - the follow relationship has been approved (automatic for non-private users)
  # "declined" - the recipient has declined this follow (recipient is a private user only)

end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :set_following, only: [:show, :edit, :update, :destroy]

  # GET /followings
  # GET /followings.json
  def index
    @followings = Following.all
  end

  # GET /followings/1
  # GET /followings/1.json
  def show
  end

  # GET /followings/new
  def new
    @following = Following.new
  end

  # GET /followings/1/edit
  def edit
  end

  # POST /followings
  # POST /followings.json
  def create
    @following = Following.new(following_params)

    respond_to do |format|
      if @following.save
        format.html { redirect_to @following, notice: 'Following was successfully created.' }
        format.json { render :show, status: :created, location: @following }
      else
        format.html { render :new }
        format.json { render json: @following.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /followings/1
  # PATCH/PUT /followings/1.json
  def update
    respond_to do |format|
      if @following.update(following_params)
        format.html { redirect_to @following, notice: 'Following was successfully updated.' }
        format.json { render :show, status: :ok, location: @following }
      else
        format.html { render :edit }
        format.json { render json: @following.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followings/1
  # DELETE /followings/1.json
  def destroy
    @following.destroy
    respond_to do |format|
      format.html { redirect_to followings_url, notice: 'Following was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # POST /followings/approve/:user_id
  def approve
    @user = current_user
    @requestor = User.find(params[:user_id])
    @following = @requestor.followings.where(:followed => @user).first
    @following.status = "approved"
    @following.save
    respond_with(@following)
  end

  # POST /followings/decline/:user_id
  def decline
    @user = current_user
    @requestor = User.find(params[:user_id])
    @following = @requestor.followings.where(:followed => @user).first
    @following.status = "declined"
    @following.save
    respond_with(@following)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_following
      @following = Following.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def following_params
      params.require(:following).permit(:status)

    end
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/views/followings/_form.html.erb
<%= form_for(@following, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @following.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@following.errors.count, "error") %> prohibited this following from being saved:</h4>

      <ul>
      <% @following.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/followings/edit.html.erb
<div class="page-header">
  <%= link_to followings_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @following, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing following</h1>
</div>

<%= render 'form' %>

app/views/followings/index.html.erb
<div class="page-header">
  <%= link_to new_following_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Following
  <% end %>
  <h1>Listing followings</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @followings) do |following| %>
            <td><%= link_to 'Show', following %></td>
        <td><%= link_to 'Edit', edit_following_path(following) %></td>
        <td><%= link_to 'Destroy', following, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/followings/new.html.erb
<div class="page-header">
  <%= link_to followings_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New following</h1>
</div>

<%= render 'form' %>

app/views/followings/show.html.erb
<div class="page-header">
  <%= link_to followings_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_following_path(@following), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show following</h1>
</div>

<dl class="dl-horizontal">
</dl>