config/routes.rb
Rails.application.routes.draw do

  resources :snapshot_comments

  mount Upmin::Engine => '/admin'

  root to: 'visitors#index'

  post "/users/me" => "users#me"
  get "/users/feed" => "users#feed"
  get "/users/:user_id/friends" => "users#friends"
  get "/users/friends" => "users#friends"
  get "/users/:user_id/followers" => "users#followers"
  get "/users/followers" => "users#followers"
  get "/users/media" => "users#media"
  get "/users/:user_id/media" => "users#media"
  get "/friend/:friend_id" => "users#friend"
  post "/users/:user_id/follow" => "users#follow"
  post "/users/:user_id/unfollow" => "users#unfollow"
  post "/users/near_me" => "users#near_me"
  post "/users/register_notifications" => "users#register_notifications"
  post "/users/unregister_notifications" => "users#unregister_notifications"
  post "/password/reset" => "passwords#reset_password"


  post "/followings/approve/:user_id" => "followings#approve"
  post "/followings/decline/:user_id" => "followings#decline"

  get "/schools/:school_id/members" => "schools#members"

  post "/schools/:school_id/follow" => "schools#follow"
  post "/schools/:school_id/unfollow" => "schools#unfollow"

  post "/comments/:comment_id/flag" => "comments#flag"
  post "/comments/:comment_id/unflag" => "comments#unflag"

  post "/comments/:comment_id/like" => "comments#like"
  post "/comments/:comment_id/unlike" => "comments#unlike"

  post "/comments/:comment_id/dislike" => "comments#dislike"
  post "/comments/:comment_id/undislike" => "comments#undislike"

  post "/snapshots/:snapshot_id/flag" => "snapshots#flag"
  post "/snapshots/:snapshot_id/unflag" => "snapshots#unflag"

  post "/snapshots/:snapshot_id/like" => "snapshots#like"
  post "/snapshots/:snapshot_id/unlike" => "snapshots#unlike"

  post "/snapshots/:snapshot_id/dislike" => "snapshots#dislike"
  post "/snapshots/:snapshot_id/undislike" => "snapshots#undislike"

  get "/snapshots/:snapshot_id/feed" => "snapshots#feed"

  get "/messages/:recipient_id/chat" => "messages#chat"
  post "/messages/:id/time" => "messages#viewed_time"


  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}

  resources :users
  resources :snapshots
  resources :comments
  resources :schools
  resources :messages
  resources :followings


end

app/models/message.rb
class Message < ActiveRecord::Base
  mount_uploader :media, MediaUploader

  belongs_to :user
  belongs_to :recipient, :class_name => 'User'

  has_many :chat_alerts
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy, :viewed_time]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.user = current_user

    @recipient = User.find(@message.recipient_id)

    puts ">>>>>>>>>>>>>> Message Create from #{current_user.id}: #{current_user.first_name} #{current_user.last_name} to #{@recipient.id}: #{@recipient.first_name} #{@recipient.last_name}"

    if @message.detail.nil? or @message.detail.empty?
      @recipient.send_alert(current_user.first_name + " " + current_user.last_name + ": sent a media file")
    else
      @recipient.send_alert(current_user.first_name + " " + current_user.last_name + ": " + @message.detail)
    end

    @recipient.increment_badge

    @message.save

    # puts "JHRLOG: new snapshot is created, lacking the image"
    # if params[:message]
    #   puts "JHRLOG: >>>>>> MESSAGE"
    # end
    #
    # if params[:message][:media_path]
    #   puts "JHRLOG: >>>>>> MESSAGE and MEDIA PATH"
    # end
    #
    # if params[:message][:media_path]["media_file"]
    #   puts "JHRLOG: >>>>>> MESSAGE and MEDIA PATH and MEDIA FILE"
    # end
    #
    #

    #check if file is within picture_path
    # if(params.has_key?(:message) && params.has_key?(:media_path) && params.has_key?("media_file"))

    if params[:message] && params[:message][:media_path] && params[:message][:media_path]["media_file"]
      # puts "JHRLOG: found a file entry"

      incoming_filename = params[:message][:media_path][:filename]


      media_path_params = params[:message][:media_path]

      #create a new tempfile named fileupload

      tempfile = Tempfile.new(incoming_filename, Rails.root.join('tmp'))

      # puts"JHRLOG: tempfile opened at #{tempfile.path}"

      tempfile.binmode
      # puts"JHRLOG: tempfile binmode set"

      # the buffer may be coming in with a base64 descriptor... trim it off the front
      # base64file = snapshot_path_params["snapshot_file"].partition(',').last
      base64file = media_path_params["media_file"]


      #get the file and decode it with base64 then write it to the tempfile
      # tempfile.write(URI::unescape(CGI::escape(Base64.decode64(base64file))))
      tempfile.write(Base64.decode64(base64file))

      # puts "JHRLOG: tempfile size after decode64 is #{tempfile.size}"

      #create a new uploaded file
      uploaded_file = ActionDispatch::Http::UploadedFile.new(:tempfile => tempfile, :filename => incoming_filename, :original_filename => incoming_filename)

      # puts "JHRLOG: uploaded file object has been created "

      #replace photo element with the new uploaded file
      # params[:snapshot][:photo] = uploaded_file

      @message.media = uploaded_file

      if incoming_filename.end_with? "mov"
        @message.timer_left = 30
      else
        @message.timer_left = 15
      end


      # puts "JHRLOG: snapshot has been assigned an upload image"
      if @message.save
        # puts "JHRLOG: snapshot has been saved with the image"
        tempfile.unlink
      end


    end

    # puts "JHRLOG: after the base64 file processing"

    # record the unviewed message

    @message.reload

    ca = ChatAlert.new()
    ca.user = current_user
    ca.recipient = @recipient
    ca.message = @message
    ca.save

    respond_with(@message)
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /messages/:id/time
  def viewed_time

    puts "####### inside viewed_time"

    if params[:timer_left]
      puts '********** found a value, saving it'
      @message.timer_left = params[:timer_left]
      @message.save
      respond_with(@message)
    end
  end

  # returns the chat conversation between the recipient and me in ascending order
  # input expects a recipient_id value in the params array
  def chat
    partner = User.find(params[:recipient_id])

    # sort descending
    # (Message.where(:user => u, :recipient =>p) + Message.where(:user => p, :recipient => u)).sort_by{|e| -e[:id]}

    # @messages = (Message.where(:user => current_user, :recipient =>partner) + Message.where(:user => partner, :recipient => current_user)).sort_by{|e| e[:id]}

    # clear all the old chat alerts
    (Message.where(:user => current_user, :recipient =>partner) + Message.where(:user => partner, :recipient => current_user)).each {|m| m.chat_alerts.where(:recipient => current_user).destroy_all}

    @messages = (Message.where(:user => current_user, :recipient =>partner, created_at: 24.hours.ago..DateTime.now) + Message.where(:user => partner, :recipient => current_user, created_at: 24.hours.ago..DateTime.now)).sort_by{|e| e[:id]}

    # remove all the chat alerts associated with this message since the recipient is now presumably viewing it
    # @messages.each {|m| m.chat_alerts.where(:recipient => current_user).destroy_all}

    respond_with(@messages)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:user_id, :recipient_id, :detail, :media, :media_cache)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @message.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h4>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/messages/edit.html.erb
<div class="page-header">
  <%= link_to messages_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @message, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing message</h1>
</div>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class="page-header">
  <%= link_to new_message_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Message
  <% end %>
  <h1>Listing messages</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @messages) do |message| %>
            <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/messages/new.html.erb
<div class="page-header">
  <%= link_to messages_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New message</h1>
</div>

<%= render 'form' %>

app/views/messages/show.html.erb
<div class="page-header">
  <%= link_to messages_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_message_path(@message), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show message</h1>
</div>

<dl class="dl-horizontal">
</dl>