config/routes.rb
Rails.application.routes.draw do

  resources :snapshot_comments

  mount Upmin::Engine => '/admin'

  root to: 'visitors#index'

  post "/users/me" => "users#me"
  get "/users/feed" => "users#feed"
  get "/users/:user_id/friends" => "users#friends"
  get "/users/friends" => "users#friends"
  get "/users/:user_id/followers" => "users#followers"
  get "/users/followers" => "users#followers"
  get "/users/media" => "users#media"
  get "/users/:user_id/media" => "users#media"
  get "/friend/:friend_id" => "users#friend"
  post "/users/:user_id/follow" => "users#follow"
  post "/users/:user_id/unfollow" => "users#unfollow"
  post "/users/near_me" => "users#near_me"
  post "/users/register_notifications" => "users#register_notifications"
  post "/users/unregister_notifications" => "users#unregister_notifications"
  post "/password/reset" => "passwords#reset_password"


  post "/followings/approve/:user_id" => "followings#approve"
  post "/followings/decline/:user_id" => "followings#decline"

  get "/schools/:school_id/members" => "schools#members"

  post "/schools/:school_id/follow" => "schools#follow"
  post "/schools/:school_id/unfollow" => "schools#unfollow"

  post "/comments/:comment_id/flag" => "comments#flag"
  post "/comments/:comment_id/unflag" => "comments#unflag"

  post "/comments/:comment_id/like" => "comments#like"
  post "/comments/:comment_id/unlike" => "comments#unlike"

  post "/comments/:comment_id/dislike" => "comments#dislike"
  post "/comments/:comment_id/undislike" => "comments#undislike"

  post "/snapshots/:snapshot_id/flag" => "snapshots#flag"
  post "/snapshots/:snapshot_id/unflag" => "snapshots#unflag"

  post "/snapshots/:snapshot_id/like" => "snapshots#like"
  post "/snapshots/:snapshot_id/unlike" => "snapshots#unlike"

  post "/snapshots/:snapshot_id/dislike" => "snapshots#dislike"
  post "/snapshots/:snapshot_id/undislike" => "snapshots#undislike"

  get "/snapshots/:snapshot_id/feed" => "snapshots#feed"

  get "/messages/:recipient_id/chat" => "messages#chat"
  post "/messages/:id/time" => "messages#viewed_time"


  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}

  resources :users
  resources :snapshots
  resources :comments
  resources :schools
  resources :messages
  resources :followings


end

app/models/school.rb
class School < ActiveRecord::Base
  mount_uploader :logo, LogoUploader

  has_many :users
  has_many :follow_schools
  has_many :followers, :through => :follow_schools, :source => :user

  has_many :comments

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  respond_to :html, :json
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  def index
    if params[:hs_search]
      hs_search = params[:hs_search]
      @schools = School.where("name ILIKE ?",  "%#{hs_search}%").order(:name)
    else
      @schools = School.order(:name)

    end
    respond_with(@schools)
  end

  def show
    respond_with(@school)
  end

  def new
    @school = School.new
    respond_with(@school)
  end

  def edit
  end

  def create
    @school = School.new(school_params)
    @school.save
    respond_with(@school)
  end

  def update
    @school.update(school_params)
    @school.logo = params[:file]
    @school.save
    respond_with(@school)
  end

  def follow
    @user = current_user
    if params[:school_id]
      @user.followed_schools << School.find(params[:school_id])
    end
  end

  def unfollow
    @user = current_user
    if params[:school_id]
      @user.followed_schools.destroy(School.find(params[:school_id]))
    end
  end

  def members
    @school = School.find(params[:school_id])
    respond_with(@school)
  end

  def destroy
    @school.destroy
    respond_with(@school)
  end

  private
    def set_school
      @school = School.find(params[:id])
    end

    def school_params
      params.require(:school).permit(:name, :address, :city, :state, :zip, :maplink, :stype, :grades, :website, :logo, :logo_cache)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school, :html => { :class => "form-horizontal" , :multipart => true }) do |f| %>
  <% if @school.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h4>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :city, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :state, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :zip, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :zip, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :maplink, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :maplink, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :stype, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :stype, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :grades, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :grades, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :website, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :website, :class => "form-control" %>
    </div>
  </div>

    <div class="form-group">
        <%= f.label :logo, :class => "col-sm-2 control-label" %>
        <div class="col-sm-10">
            <%= f.file_field :logo, :class => "form-control" %>
            <%= f.hidden_field :logo_cache %>
        </div>
    </div>




  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/schools/edit.html.erb
<div class="page-header">
  <%= link_to schools_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @school, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing school</h1>
</div>

<%= render 'form' %>

app/views/schools/index.html.erb
<div class="page-header">
  <%= link_to new_school_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New School
  <% end %>
  <h1>Listing schools</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Zip</th>
            <th>Type</th>
            <th>Grades</th>
            <th>Logo</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @schools) do |school| %>
            <td><%= school.name %></td>
            <td><%= school.address %></td>
            <td><%= school.city %></td>
            <td><%= school.state %></td>
            <td><%= school.zip %></td>
            <td><%= school.stype %></td>
            <td><%= school.grades %></td>
            <td><%= image_tag(school.logo.thumb.url) if school.logo? %></td>
            <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/schools/new.html.erb
<div class="page-header">
  <%= link_to schools_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New school</h1>
</div>

<%= render 'form' %>

app/views/schools/show.html.erb
<div class="page-header">
  <%= link_to schools_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_school_path(@response.school), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show school</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @response.school.name %></dd>

  <dt>Address:</dt>
  <dd><%= @response.school.address %></dd>

  <dt>City:</dt>
  <dd><%= @response.school.city %></dd>

  <dt>State:</dt>
  <dd><%= @response.school.state %></dd>

  <dt>Zip:</dt>
  <dd><%= @response.school.zip %></dd>

  <dt>Maplink:</dt>
  <dd><%= @response.school.maplink %></dd>

  <dt>Type:</dt>
  <dd><%= @response.school.stype %></dd>

  <dt>Grades:</dt>
  <dd><%= @response.school.grades %></dd>

  <dt>Website:</dt>
  <dd><%= @response.school.website %></dd>

    <dt>Full-Size Logo:</dt>
    <dd><%= image_tag(@response.school.logo.url) if @response.school.logo? %></dd>

    <dt>Large Logo:</dt>
    <dd><%= image_tag(@response.school.logo.large.url) if @response.school.logo? %></dd>

    <dt>Medium Logo:</dt>
    <dd><%= image_tag(@response.school.logo.medium.url) if @response.school.logo? %></dd>

    <dt>Thumb Logo:</dt>
    <dd><%= image_tag(@response.school.logo.thumb.url) if @response.school.logo? %></dd>

    <dt>Small Logo:</dt>
    <dd><%= image_tag(@response.school.logo.small.url) if @response.school.logo? %></dd>

</dl>